dataset: 'xrf2'
t_his: 75  # 历史帧
t_pred: 75  # 预测帧
batch_size: 64
num_epoch: 1001  # 有多少个epoch
num_data_sample: 15000  # 每个epoch训练用多少组数据
num_val_data_sample: 1500  # 每个epoch测试用多少组数据
lr: 3.e-4  # 初始学习率
lr_decay_every: 10  # 学习率多少轮下降一次
lr_decay_rate: 0.9  # 学习率下降时的比率
lr_limit: 1.e-6  # 学习率最低值
train_path: E:/xrf2/train  # 训练集位置
test_path: E:/xrf2/test  # 测试集位置

# 以下参数建议不要改
n_pre: 20  # DCT变换后的行数
multimodal_path: ./data/data_multi_modal/t_his25_1_thre0.500_t_pred100_thre0.100_filtered_dlow.npz  # 多模态，不用
data_candi_path: ./data/data_multi_modal/data_candi_t_his25_t_pred100_skiprate20.npz  # 多模态，不用
padding: 'LastFrame'  # padding的方式，LastFrame表示用已知的最后一帧反复复制粘贴填满
Complete: True
noise_steps: 1000
ddim_timesteps: 100
scheduler: 'Cosine' # 'Cosine' 'Linear' 'Sqrt' 'Sigmoid'
num_layers: 8
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 0.8
mod_test: 1.0
dct_norm_enable: False